version: '3.7'

services:
  generic:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/nestjs-apis:/app
    working_dir: /app
  gateway:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/nestjs-apis:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run start:dev gateway
