import type { App } from "vue";
import AlertVue from "./components/Alert.vue";
import ButtonVue from "./components/Button.vue";
import CalendarVue from "./components/Calendar.vue";
import CardVue from "./components/Card.vue";
import DataTableVue from "./components/DataTable.vue";
import AutocompleteVue from "./components/form/Autocomplete.vue";
import DatePickerVue from "./components/form/DatePicker.vue";
import FormVue from "./components/form/Form.vue";
import PasswordInputVue from "./components/form/PasswordInput.vue";
import RadioGroupVue from "./components/form/RadioGroup.vue";
import SelectVue from "./components/form/Select.vue";
import SwitchVue from "./components/form/Switch.vue";
import TextFieldVue from "./components/form/TextField.vue";
import IconVue from "./components/Icon.vue";
import IconButtonVue from "./components/IconButton.vue";
import MenuVue from "./components/Menu.vue";
import ModalVue from "./components/Modal.vue";
import PaginationVue from "./components/Pagination.vue";
import SidebarVue from "./components/Sidebar.vue";
import SpinnerVue from "./components/Spinner.vue";
import TableVue from "./components/Table.vue";
import TabsVue from "./components/Tabs.vue";
import ToastVue from "./components/Toast.vue";

export default async function setupComponents(app: App) {
  app.component("m-tabs", TabsVue);
  app.component("m-button", ButtonVue);
  app.component("m-table", TableVue);
  app.component("m-datatable", DataTableVue);
  app.component("m-textfield", TextFieldVue);
  app.component("m-datepicker", DatePickerVue);
  app.component("m-select", SelectVue);
  app.component("m-switch", SwitchVue);
  app.component("m-radiogroup", RadioGroupVue);
  app.component("m-autocomplete", AutocompleteVue);
  app.component("m-form", FormVue);
  app.component("m-icon", IconVue);
  app.component("m-iconbutton", IconButtonVue);
  app.component("m-menu", MenuVue);
  app.component("m-modal", ModalVue);
  app.component("m-sidebar", SidebarVue);
  app.component("m-pagination", PaginationVue);
  app.component("m-spinner", SpinnerVue);
  app.component("m-toast", ToastVue);
  app.component("m-card", CardVue);
  app.component("m-calendar", CalendarVue);
  app.component("m-passwordinput", PasswordInputVue);
  app.component("m-alert", AlertVue);
}
